# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
