# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
